MAINT: update workflows

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -7,24 +7,22 @@ name: Galaxy Tool Linting and Tests for push and PR
 on:
   push:
     branches: [main]
-    paths-ignore:
+    paths:
       # The rendering has 2 phases: 1st is updating distros which issues a PR,
       # that PR has the changes which are then tested by this action.
-      - 'distros.yaml'
-      - 'repo-utils/**'
-      - 'README.md'
+      - 'tools/**'
+      - 'tool_collections/**'
   pull_request:
     branches: [main]
-    paths-ignore:
-      - 'distros.yaml'
-      - 'repo-utils/**'
-      - 'README.md'
+    paths:
+      - 'tools/**'
+      - 'tool_collections/**'
 # MODIFIED END
 env:
   GALAXY_FORK: galaxyproject
   GALAXY_BRANCH: release_24.1
-  MAX_CHUNKS: 4
-  MAX_FILE_SIZE: 1M
+  MAX_CHUNKS: 6 # MODIFIED
+  MAX_FILE_SIZE: 10M # MODIFIED - sorry :'(
 concurrency:
   # Group runs by PR, but keep runs on the default branch separate
   # because we do not want to cancel ToolShed uploads
@@ -107,123 +105,125 @@ jobs:
       run: |
         echo 'Using ${{ steps.discover.outputs.chunk-count }} chunks (${{ steps.discover.outputs.chunk-list }})'
 
-  # Planemo lint the changed repositories
-  lint:
-    name: Lint tool-list
-    needs: setup
-    if: ${{ needs.setup.outputs.repository-list != '' || needs.setup.outputs.tool-list != '' }}
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ['3.11']
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 1
-    - uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Cache .cache/pip
-      uses: actions/cache@v4
-      id: cache-pip
-      with:
-        path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
+# MODIFIED START
+  # # Planemo lint the changed repositories
+  # lint:
+  #   name: Lint tool-list
+  #   needs: setup
+  #   if: ${{ needs.setup.outputs.repository-list != '' || needs.setup.outputs.tool-list != '' }}
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ['3.11']
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     with:
+  #       fetch-depth: 1
+  #   - uses: actions/setup-python@v5
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: Cache .cache/pip
+  #     uses: actions/cache@v4
+  #     id: cache-pip
+  #     with:
+  #       path: ~/.cache/pip
+  #       key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
 
-    - name: Set fail level for pull request
-      if: ${{ github.event_name == 'pull_request' }}
-      run:
-        echo "FAIL_LEVEL=warn" >> "$GITHUB_ENV"
-    - name: Set fail level for merge
-      if: ${{ github.event_name != 'pull_request' }}
-      run:
-        echo "FAIL_LEVEL=error" >> "$GITHUB_ENV"
-    - name: Planemo lint
-      uses: galaxyproject/planemo-ci-action@v1
-      id: lint
-      with:
-        mode: lint
-        fail-level: ${{ env.FAIL_LEVEL }}
-        repository-list: ${{ needs.setup.outputs.repository-list }}
-        tool-list: ${{ needs.setup.outputs.tool-list }}
-    - uses: actions/upload-artifact@v4
-      if: ${{ failure() }}
-      with:
-        name: 'Tool linting output'
-        path: lint_report.txt
+  #   - name: Set fail level for pull request
+  #     if: ${{ github.event_name == 'pull_request' }}
+  #     run:
+  #       echo "FAIL_LEVEL=warn" >> "$GITHUB_ENV"
+  #   - name: Set fail level for merge
+  #     if: ${{ github.event_name != 'pull_request' }}
+  #     run:
+  #       echo "FAIL_LEVEL=error" >> "$GITHUB_ENV"
+  #   - name: Planemo lint
+  #     uses: galaxyproject/planemo-ci-action@v1
+  #     id: lint
+  #     with:
+  #       mode: lint
+  #       fail-level: ${{ env.FAIL_LEVEL }}
+  #       repository-list: ${{ needs.setup.outputs.repository-list }}
+  #       tool-list: ${{ needs.setup.outputs.tool-list }}
+  #   - uses: actions/upload-artifact@v4
+  #     if: ${{ failure() }}
+  #     with:
+  #       name: 'Tool linting output'
+  #       path: lint_report.txt
 
-  # flake8 of Python scripts in the changed repositories
-  flake8:
-    name: Lint Python scripts
-    needs: setup
-    if: ${{ github.event_name == 'pull_request' && needs.setup.outputs.repository-list != '' }}
-    runs-on: ubuntu-latest
-    strategy:
-      fail-fast: false
-      matrix:
-        python-version: ['3.11']
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 1
-    - uses: actions/setup-python@v5
-      with:
-        python-version: ${{ matrix.python-version }}
-    - name: Cache .cache/pip
-      uses: actions/cache@v4
-      id: cache-pip
-      with:
-        path: ~/.cache/pip
-        key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
-    - name: Install flake8
-      run: pip install flake8 flake8-import-order
-    - name: Flake8
-      run: echo '${{ needs.setup.outputs.repository-list }}' | xargs -d '\n' flake8 --output-file pylint_report.txt --tee
-    - uses: actions/upload-artifact@v4
-      if: ${{ failure() }}
-      with:
-        name: 'Python linting output'
-        path: pylint_report.txt
+  # # flake8 of Python scripts in the changed repositories
+  # flake8:
+  #   name: Lint Python scripts
+  #   needs: setup
+  #   if: ${{ github.event_name == 'pull_request' && needs.setup.outputs.repository-list != '' }}
+  #   runs-on: ubuntu-latest
+  #   strategy:
+  #     fail-fast: false
+  #     matrix:
+  #       python-version: ['3.11']
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     with:
+  #       fetch-depth: 1
+  #   - uses: actions/setup-python@v5
+  #     with:
+  #       python-version: ${{ matrix.python-version }}
+  #   - name: Cache .cache/pip
+  #     uses: actions/cache@v4
+  #     id: cache-pip
+  #     with:
+  #       path: ~/.cache/pip
+  #       key: pip_cache_py_${{ matrix.python-version }}_gxy_${{ needs.setup.outputs.galaxy-head-sha }}
+  #   - name: Install flake8
+  #     run: pip install flake8 flake8-import-order
+  #   - name: Flake8
+  #     run: echo '${{ needs.setup.outputs.repository-list }}' | xargs -d '\n' flake8 --output-file pylint_report.txt --tee
+  #   - uses: actions/upload-artifact@v4
+  #     if: ${{ failure() }}
+  #     with:
+  #       name: 'Python linting output'
+  #       path: pylint_report.txt
 
-  lintr:
-    name: Lint R scripts
-    needs: setup
-    if: ${{ needs.setup.outputs.repository-list != '' }}
-    runs-on: ${{ matrix.os }}
-    strategy:
-      matrix:
-        os: [ubuntu-20.04]
-        r-version: ['release']
-    steps:
-    - uses: actions/checkout@v4
-      with:
-        fetch-depth: 1
-    - uses: r-lib/actions/setup-r@v2
-      with:
-        r-version: ${{ matrix.r-version }}
-    - name: Cache R packages
-      uses: actions/cache@v4
-      with:
-        path: ${{ env.R_LIBS_USER }}
-        key: r_cache_${{ matrix.os }}_${{ matrix.r-version }}
-    - name: Install packages
-      uses: r-lib/actions/setup-r-dependencies@v2
-      with:
-        packages: |
-          any::argparse
-          any::styler
-    - name: lintr
-      run: |
-        set -eo pipefail
-        echo '${{ needs.setup.outputs.repository-list }}' | xargs -d '\n' -n 1 ./.github/styler.R --dry off
-        git status
-        git diff --exit-code | tee rlint_report.txt
-    - uses: actions/upload-artifact@v4
-      if: ${{ failure() }}
-      with:
-        name: 'R linting output'
-        path: rlint_report.txt
+  # lintr:
+  #   name: Lint R scripts
+  #   needs: setup
+  #   if: ${{ needs.setup.outputs.repository-list != '' }}
+  #   runs-on: ${{ matrix.os }}
+  #   strategy:
+  #     matrix:
+  #       os: [ubuntu-20.04]
+  #       r-version: ['release']
+  #   steps:
+  #   - uses: actions/checkout@v4
+  #     with:
+  #       fetch-depth: 1
+  #   - uses: r-lib/actions/setup-r@v2
+  #     with:
+  #       r-version: ${{ matrix.r-version }}
+  #   - name: Cache R packages
+  #     uses: actions/cache@v4
+  #     with:
+  #       path: ${{ env.R_LIBS_USER }}
+  #       key: r_cache_${{ matrix.os }}_${{ matrix.r-version }}
+  #   - name: Install packages
+  #     uses: r-lib/actions/setup-r-dependencies@v2
+  #     with:
+  #       packages: |
+  #         any::argparse
+  #         any::styler
+  #   - name: lintr
+  #     run: |
+  #       set -eo pipefail
+  #       echo '${{ needs.setup.outputs.repository-list }}' | xargs -d '\n' -n 1 ./.github/styler.R --dry off
+  #       git status
+  #       git diff --exit-code | tee rlint_report.txt
+  #   - uses: actions/upload-artifact@v4
+  #     if: ${{ failure() }}
+  #     with:
+  #       name: 'R linting output'
+  #       path: rlint_report.txt
+# MODIFIED END
 
   file_sizes:
     name: Check file sizes
@@ -368,8 +368,8 @@ jobs:
   # deploy the tools to the toolsheds (first TTS for testing)
   deploy:
     name: Deploy
-    needs: [setup, lint, combine_outputs]
-    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == 'galaxyproject' }}
+    needs: [setup, file_sizes, combine_outputs]  # MODIFIED
+    if: ${{ (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' ) && github.repository_owner == 'qiime2' }}  # MODIFIED
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -427,19 +427,21 @@ jobs:
 
   determine-success:
     name: Check workflow success
-    needs: [setup, lint, flake8, lintr, file_sizes, combine_outputs]
+    needs: [setup, file_sizes, combine_outputs]  # MODIFIED
     if: ${{ always() && github.ref != 'refs/heads/master' && github.ref != 'refs/heads/main' }}
     runs-on: ubuntu-latest
     steps:
-    - name: Check tool lint status
-      if: ${{ needs.lint.result != 'success' && needs.flake8.result != 'skipped' }}
-      run: exit 1
-    - name: Indicate Python script lint status
-      if: ${{ needs.flake8.result != 'success' && needs.flake8.result != 'skipped' }}
-      run: exit 1
-    - name: Indicate R script lint status
-      if: ${{ needs.lintr.result != 'success' && needs.lintr.result != 'skipped' }}
-      run: exit 1
+# MODIFIED START
+    # - name: Check tool lint status
+    #   if: ${{ needs.lint.result != 'success' && needs.flake8.result != 'skipped' }}
+    #   run: exit 1
+    # - name: Indicate Python script lint status
+    #   if: ${{ needs.flake8.result != 'success' && needs.flake8.result != 'skipped' }}
+    #   run: exit 1
+    # - name: Indicate R script lint status
+    #   if: ${{ needs.lintr.result != 'success' && needs.lintr.result != 'skipped' }}
+    #   run: exit 1
+# MODIFIED END
     - name: Indicate file size check status
       if: ${{ needs.file_sizes.result != 'success' && needs.file_sizes.result != 'skipped' }}
       run: exit 1
